theme: jekyll-theme-minimal

title: Alexis Reyes Jr
description: Father, Husband  - Solutions Engineer @[DigitalOcean](https://www.digitalocean.com/)
logo: /assets/img/logo.png
github.is_user_page: false
